// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXyi3NrPynC3uEv-D9cXh9yzcdiaLYN40',
    appId: '1:650776736717:web:376ce3a2533415f2e3ca84',
    messagingSenderId: '650776736717',
    projectId: 'bookstore53-f0c56',
    authDomain: 'bookstore53-f0c56.firebaseapp.com',
    storageBucket: 'bookstore53-f0c56.firebasestorage.app',
    measurementId: 'G-CCSC7KH07C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyHEjDh19BBdW28YBDocsKkIUlWHtiD0',
    appId: '1:650776736717:android:994b3b9f9d26b98ce3ca84',
    messagingSenderId: '650776736717',
    projectId: 'bookstore53-f0c56',
    storageBucket: 'bookstore53-f0c56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74qXOx7byJu4UwbXz4dp4nAF-1FSZewg',
    appId: '1:650776736717:ios:5417175856174bdfe3ca84',
    messagingSenderId: '650776736717',
    projectId: 'bookstore53-f0c56',
    storageBucket: 'bookstore53-f0c56.firebasestorage.app',
    iosBundleId: 'com.example.bookstore53',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC74qXOx7byJu4UwbXz4dp4nAF-1FSZewg',
    appId: '1:650776736717:ios:5417175856174bdfe3ca84',
    messagingSenderId: '650776736717',
    projectId: 'bookstore53-f0c56',
    storageBucket: 'bookstore53-f0c56.firebasestorage.app',
    iosBundleId: 'com.example.bookstore53',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXyi3NrPynC3uEv-D9cXh9yzcdiaLYN40',
    appId: '1:650776736717:web:6a5325b16b6c3e4de3ca84',
    messagingSenderId: '650776736717',
    projectId: 'bookstore53-f0c56',
    authDomain: 'bookstore53-f0c56.firebaseapp.com',
    storageBucket: 'bookstore53-f0c56.firebasestorage.app',
    measurementId: 'G-934G50DNZH',
  );
}
